actions/setup-ock: Add `shell` to `Install` step
Though this can be omitted in workflows, this is apparently required for composite actions:

> Error: slewiskelly/ock/main/.github/actions/setup-ock/action.yml (Line: 15, Col: 7): Required property is missing: shell