actions/vet: Add `shell` to `Vet` step
Though this can be omitted in workflows, this is apparently required for composite actions:

> Error: slewiskelly/ock/main/.github/actions/vet/action.yml (Line: 24, Col: 7): Required property is missing: shell